### ISSUE TITLE
get all devices from local network

### ISSUE THREAD

**Issue by George-debug** [DeliTrbat/IPProjectB2#7]
### Class : Peer
- `public static List<Integer> getDevices()`
Returnează al patrulea octet din `local adress` pentru fiecare device conectat la rețeaua locală
  - Ex:
    - 192.168.1.`130`
    - 192.168.0.`12`

  - Soluții posibile:
    - dai ping la toate adresele de forma `subnet.octet` unde octet ia valori intre 0 si 255
    - folosesti ceva similar cu `arp -a`

**Comment by StefanRoman1** [comment]
![image](https://user-images.githubusercontent.com/100143628/163339833-d399d4e2-beec-4fd2-b4d9-489dd2e21c1d.png)
ceva de genu cam trebuie sa faca functia mea, in a doua poza am mai conectat un laptop la net gen
